### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'past'

### ISSUE THREAD

**Issue by JustSaX** [RF5/lmao#14]
Hi I get the following error message:

`TypeError: forward() got an unexpected keyword argument 'past'
in:
`endpoints/views.py", line 62, in gpt2_infer
    output, past = model(context, past=past)`

I couldn't the gpt2small.zip model you described and used the following model: https://huggingface.co/gpt2/tree/main

Am I using the correct model?

Thanks!

**Comment by RF5** [comment]
Ahh yes, this appears to be a chance in the Huggingface `transformers` library when it changed from v3 to v4, which introduced many backwards incompatible changes. I think I accidentally set the `transformers` library version requirement as v4 in the `requirements.txt`. 

I have updated the `requirements.txt` now to indicate that it requires v3 instead of v4. So I think it should be fixed if you downgrade your `transfromers` version, or change how the past is provided to the model according to how Huggingface `transformers` v4 requires.

**Comment by JustSaX** [comment]
Thanks for the quick reply.

I created a new env and used transformer v3 from your updated requirements.txt. Now I get the following error:
`TypeError: Couldn't build proto file into descriptor pool: duplicate file name (sentencepiece_model.proto)`

**Comment by RF5** [comment]
Hmm, I suspect this might be because the newer model you are downloading from huggingface is serialised for transformers v4, so transformers v3 won't read it properly. Either that or there is some other dependency issue on sentencepiece.

I think you may need to use my model checkpoint instead (under the releases tab), or change how the model is called to work with all the newer (and probably much better) huggingface models and transformers v4.

**Comment by JustSaX** [comment]
Now I understand to find your model, I didn't realize you mean the release tab in Github.
It works now, there was a problem with protobuf. I had to uninstall it `pip uninstall protobuf` and reinstall with `pip install --no-binary protobuf protobuf` Ref: [https://github.com/protocolbuffers/protobuf/issues/3002](url)

Thanks for your help!
